kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: loadbalancer
  # Magic to bind the loadbalancing address
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "chmsqrt2-truesparrow-staging-loadbalancer-address"
    ingress.gcp.kubernetes.io/pre-shared-cert: "chmsqrt2-truesparrow-staging-loadbalancer-newnew-certificate"
spec:
  rules:
  - host: adminfe.staging.truesparrow.chm-sqrt2.io
    http:
      paths:
      - backend:
          serviceName: adminfe
          servicePort: 80
  - host: sitefe.staging.truesparrow.chm-sqrt2.io
    http:
      paths:
      - backend:
          serviceName: sitefe
          servicePort: 80
  - host: "*.sitefe.staging.truesparrow.chm-sqrt2.io"
    http:
      paths:
      - backend:
          serviceName: sitefe
          servicePort: 80
